// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildLink(arg1) {
  return window['go']['main']['App']['BuildLink'](arg1);
}

export function ConfigCommand(arg1) {
  return window['go']['main']['App']['ConfigCommand'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CoreVersion() {
  return window['go']['main']['App']['CoreVersion']();
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GenerateClientID() {
  return window['go']['main']['App']['GenerateClientID']();
}

export function GenerateObfKey() {
  return window['go']['main']['App']['GenerateObfKey']();
}

export function ImportLink(arg1, arg2) {
  return window['go']['main']['App']['ImportLink'](arg1, arg2);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function NewServer() {
  return window['go']['main']['App']['NewServer']();
}

export function ParseLink(arg1) {
  return window['go']['main']['App']['ParseLink'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function ServerLogs(arg1, arg2) {
  return window['go']['main']['App']['ServerLogs'](arg1, arg2);
}

export function ServerPeerAdd(arg1, arg2) {
  return window['go']['main']['App']['ServerPeerAdd'](arg1, arg2);
}

export function ServerPeerRemove(arg1, arg2) {
  return window['go']['main']['App']['ServerPeerRemove'](arg1, arg2);
}

export function ServerPeerShare(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ServerPeerShare'](arg1, arg2, arg3, arg4);
}

export function ServerPeers(arg1) {
  return window['go']['main']['App']['ServerPeers'](arg1);
}

export function ServerRemoteStatus(arg1) {
  return window['go']['main']['App']['ServerRemoteStatus'](arg1);
}

export function ServerRestart(arg1) {
  return window['go']['main']['App']['ServerRestart'](arg1);
}

export function ServerStop(arg1) {
  return window['go']['main']['App']['ServerStop'](arg1);
}

export function ServerUninstall(arg1, arg2) {
  return window['go']['main']['App']['ServerUninstall'](arg1, arg2);
}

export function SetupCreateServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupCreateServer'](arg1, arg2, arg3);
}

export function SetupDetectRootMode(arg1) {
  return window['go']['main']['App']['SetupDetectRootMode'](arg1);
}

export function SetupInstall(arg1) {
  return window['go']['main']['App']['SetupInstall'](arg1);
}

export function SetupProbe(arg1) {
  return window['go']['main']['App']['SetupProbe'](arg1);
}

export function SetupStart(arg1, arg2) {
  return window['go']['main']['App']['SetupStart'](arg1, arg2);
}

export function SetupWgSetup(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupWgSetup'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function VPNAvailable() {
  return window['go']['main']['App']['VPNAvailable']();
}
