// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {serversetup} from '../models';

export function BuildLink(arg1:backend.Server):Promise<string>;

export function ConfigCommand(arg1:string):Promise<string>;

export function Connect(arg1:string):Promise<void>;

export function CopyText(arg1:string):Promise<void>;

export function CoreVersion():Promise<string>;

export function DeleteServer(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GenerateClientID():Promise<string>;

export function GenerateObfKey():Promise<string>;

export function ImportLink(arg1:string,arg2:backend.Server):Promise<backend.Server>;

export function ListServers():Promise<Array<backend.Server>>;

export function NewServer():Promise<backend.Server>;

export function ParseLink(arg1:string):Promise<backend.ShareLink>;

export function SaveServer(arg1:backend.Server):Promise<backend.Server>;

export function ServerLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function ServerPeerAdd(arg1:string,arg2:string):Promise<backend.GuestShare>;

export function ServerPeerRemove(arg1:string,arg2:string):Promise<void>;

export function ServerPeerShare(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<backend.GuestShare>;

export function ServerPeers(arg1:string):Promise<serversetup.PeerList>;

export function ServerRemoteStatus(arg1:string):Promise<serversetup.ProbeResult>;

export function ServerRestart(arg1:string):Promise<void>;

export function ServerStop(arg1:string):Promise<void>;

export function ServerUninstall(arg1:string,arg2:boolean):Promise<serversetup.UninstallResult>;

export function SetupCreateServer(arg1:serversetup.SSHConfig,arg2:backend.ServerSetupDraft,arg3:serversetup.WgSetupResult):Promise<backend.Server>;

export function SetupDetectRootMode(arg1:serversetup.SSHConfig):Promise<serversetup.SSHConfig>;

export function SetupInstall(arg1:serversetup.SSHConfig):Promise<serversetup.InstallResult>;

export function SetupProbe(arg1:serversetup.SSHConfig):Promise<serversetup.ProbeResult>;

export function SetupStart(arg1:serversetup.SSHConfig,arg2:serversetup.StartOptions):Promise<void>;

export function SetupWgSetup(arg1:serversetup.SSHConfig,arg2:number,arg3:string):Promise<serversetup.WgSetupResult>;

export function Status():Promise<backend.Status>;

export function VPNAvailable():Promise<boolean>;
